### ISSUE TITLE
Add EE courses

### ISSUE THREAD

**Issue by RiceAbove** [RiceAbove/BSOE-New-Course-Search#4]
**Is your feature request related to a problem? Please describe.**
Almost all of the courses in BSOE are searchable except for EE. This prevents EE students (or students taking EE courses), from knowing what classes they need to take based off of the old class codes.

**Describe the solution you'd like**
We couldn't get the EE courses because it has a different HTML tag than the other ones. I would like the EE courses to be added to the main.js file using the python script included in the source files.

**Comment by safelock** [comment]
EE Support tentatively added. Comment and reopen if there are any issues.
